CREATE TABLE PIZZA (id INT NOT NULL UNIQUE, name TEXT NOT NULL, price REAL NOT NULL, PRIMARY KEY(id));

CREATE TABLE ORDER (id INT NOT NULL UNIQUE, details TEXT NOT NULL, total REAL NOT NULL, PRIMARY KEY(id));

CREATE SEQUENCE hibernate_sequence START 1;